
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import React from 'react';


const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'agile app',
	description: 'Generated by agile app',
};


export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div style={{ background: '#f6f8fa', borderBottom: '1px solid #d0d7de', padding: '12px 24px' }}>
					<span style={{ fontWeight: 700, fontSize: '1.1rem', color: '#24292f' }}>agile app</span>
				</div>
				<div style={{ background: '#fff', minHeight: '100vh' }}>
					{children}
				</div>
			</body>
		</html>
	);
}
